#Load data single dwell times (P:A_coef)
```{r}
library(readxl)
library(dplyr)
dwell <- read_excel("../Data/summary_single_DT.xlsx", 
    col_types = c("numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "text", "text", "text", "text"))

dwell <- as.data.frame(dwell)
dwell <- dwell %>%
  select(-starts_with("Nag_"))

dwell$codon <- gsub("T", "U", dwell$codon)
dwell$name <- gsub("T", "U", dwell$name)
```
## Calculate mean values and p-values over multiple positions
```{r}
library(dplyr)
library(ggrepel)

calculate_means <- function(dataframe, pattern) {
  cols <- grep(pattern, names(dataframe), value = TRUE)
  rowMeans(dataframe[, cols], na.rm = TRUE)
}
conditions <- c("CTRL", "DOUBLE", "ILE", "LEU", "TRIPLE", "VAL")
result_df <- dwell %>% select(aa, codon, pos, name)

for(condition in conditions) {
  pattern <- paste0("Lina_", condition, "_[1-3]")
  result_df[[condition]] <- calculate_means(dwell, pattern)
}

dwell_filtered <- result_df %>%
  filter(pos %in% c("-2","-1", "E", "P", "A", "3", "4")) %>%
  select(-pos, -name)%>%
  group_by(codon) %>%
  mutate(across(c(CTRL, DOUBLE, ILE, LEU, TRIPLE, VAL), mean, na.rm = TRUE)) %>%
  ungroup() %>%
  distinct(codon, .keep_all = TRUE)

##p-value calculation
library(tidyr)
library(dplyr)

dwell_long <- dwell %>%
  filter(pos %in% c("-2","-1", "E", "A", "P", "3", "4"))%>%
  pivot_longer(
    cols = starts_with("Lina_"), 
    names_to = "condition", 
    names_prefix = "Lina_", 
    values_to = "dwell_time"
  ) %>%
  mutate(condition = factor(gsub("_[0-9]+$", "", condition)))

results <- list()
unique_codons <- unique(dwell_long$codon)
for(codon in unique_codons){
    dwell_long_subset <- dwell_long %>% filter(codon == !!codon)
    if(nrow(dwell_long_subset) > 2 && length(unique(dwell_long_subset$condition)) > 1) {
      model <- aov(dwell_time ~ condition, data = dwell_long_subset)
      post_hoc <- TukeyHSD(model)
      results[[paste(codon, sep = "_")]] <- post_hoc
    } else {
      results[[paste(codon, sep = "_")]] <- NA
    }
  }

final_results <- data.frame(codon = character(),p_adj_LEU = numeric(),p_adj_ILE = numeric(),p_adj_VAL = numeric(),p_adj_DOUBLE = numeric(),p_adj_TRIPLE = numeric(),stringsAsFactors = FALSE)

for(key in names(results)){
  if(!is.na(results[[key]])){
    codon <- key
    
    p_adj_LEU <- NA
    p_adj_ILE <- NA
    p_adj_VAL <- NA
    p_adj_DOUBLE <- NA
    p_adj_TRIPLE <- NA
    
    post_hoc <- results[[key]]
    comparisons <- post_hoc$`condition`[, "p adj"]
    comparison_names <- rownames(post_hoc$`condition`)
    
    for(comp in c("LEU-CTRL", "ILE-CTRL", "VAL-CTRL", "DOUBLE-CTRL", "TRIPLE-CTRL")){
      comp_index <- grep(comp, comparison_names)
      if(length(comp_index) > 0){
        p_value <- comparisons[comp_index]
        if(comp == "LEU-CTRL") p_adj_LEU <- p_value
        if(comp == "ILE-CTRL") p_adj_ILE <- p_value
        if(comp == "VAL-CTRL") p_adj_VAL <- p_value
        if(comp == "DOUBLE-CTRL") p_adj_DOUBLE <- p_value
        if(comp == "TRIPLE-CTRL") p_adj_TRIPLE <- p_value
      }
    }
  
    final_results <- rbind(final_results, data.frame(
      codon = codon, 
      p_adj_LEU = p_adj_LEU, 
      p_adj_ILE = p_adj_ILE,
      p_adj_VAL = p_adj_VAL, 
      p_adj_DOUBLE = p_adj_DOUBLE, 
      p_adj_TRIPLE = p_adj_TRIPLE
    ))
  }
}

dwell_filtered <- merge(dwell_filtered, final_results, by = "codon", all.x = TRUE)
rm(final_results, dwell_long, dwell_long_subset, post_hoc, results, model)
```

# Correlation of dwell time and codon frequency in mouse genome
```{r}
library(readxl)
load(file="../../General_datasets/datatable_Riboseq_normalized.RData")
codons <- read_excel("../../General_datasets/codon_counts_LNorm_mouse.xlsx")

data$codons <- gsub("T", "U", data$codons)
colnames(codons) <- gsub("T", "U", colnames(codons))

codon_frequency <- codons %>%
  filter(Gene %in% data$gene_symbol)%>%
  select(-Gene) %>%
  summarise(across(everything(), mean, na.rm = TRUE))%>%
  pivot_longer(cols = everything(), names_to = "Codon", values_to = "Frequency")

val_codons <- c("GUA", "GUC", "GUG", "GUU")
ile_codons <- c("AUA", "AUC", "AUU")
leu_codons <- c("CUA", "CUC", "CUG", "CUU", "UUA", "UUG")

codon_frequency <- codon_frequency %>%
  mutate(Type = case_when(
    Codon %in% val_codons ~ "Val",
    Codon %in% ile_codons ~ "Ile",
    Codon %in% leu_codons ~ "Leu",
    TRUE ~ "Other"
  ))

## SCATTER PLOT dwell times CTRL and CODON FREQUENCIES
dwell_filtered2 <- merge(dwell_filtered, codon_frequency, by.x = "codon", by.y = "Codon")%>%
  mutate(diff_Double = DOUBLE - CTRL,
         diff_Triple = TRIPLE - CTRL,
         diff_Val = VAL- CTRL,
         diff_Ile = ILE-CTRL,
         diff_Leu = LEU-CTRL)

conditions <- c("diff_Double", "diff_Triple", "diff_Leu", "diff_Ile", "diff_Val")

plot_scatter <- function(cond_column){

  # Create the plot
  scatter_plot <- ggplot(dwell_filtered2, aes(y = .data[[cond_column]], x = Frequency * 100)) +
    geom_point(aes(fill = Type, size = ifelse(Type %in% c("Val", "Ile", "Leu"), 3, 1)), shape = 21) +
    scale_fill_manual(values = c("Val" = "#FF7F00", "Ile" = "#377EB8", "Leu" = "#4DAF4A", "Other" = "black")) +
    scale_size_identity() +
    geom_smooth(method = "lm", se = FALSE, color = "red") +
    geom_text_repel(
      data = dwell_filtered2 %>% filter(Type %in% c("Val", "Ile", "Leu")),
      aes(label = codon),
      vjust = -1, color = "black", max.overlaps = Inf,
      nudge_y = 0.1, segment.color = "grey50", segment.size = 0.5, size = 4, family = "Arial"
    ) +
    coord_cartesian(ylim = c(-0.3,1))+
    labs(
      title = NULL,
      y = paste0("DTs (", cond_column, ", log2FC)"),
      x = "Codon frequency (%)",
      fill = "Codon"
    ) +
    theme_classic(base_family = "Arial") +
    theme(
      plot.background = element_rect(fill = "transparent", colour = NA),
      panel.background = element_rect(fill = "transparent", colour = NA),
      axis.ticks = element_line(colour = "black"),
      axis.title = element_text(size = 14, face = "plain", color = "black"),
      axis.text = element_text(size = 14, face = "plain", color = "black"),
      legend.title = element_text(size = 14, color = "black", face = "plain"),
      legend.background = element_rect(fill = "transparent", colour = NA),
      legend.text = element_text(size = 14, color = "black", face = "plain"),
      legend.position = "right"
    )

  # Save plot
  ggsave(
    filename = paste0("../Figures/Revision/scatter_DT_Codon_frequencies_", cond_column, ".png"),
    plot = scatter_plot,
    width = 6, height = 3, units = "in", dpi = 300
  )

  return(scatter_plot)
}

for (cond in conditions) {
  plot_scatter(cond)
}
```


```{r}
library(dplyr)
library(ggrepel)

result_df2 <- dwell %>%
  select(Lina_CTRL_1, Lina_CTRL_2, aa, codon, name, pos)%>%
  mutate(Ctrl_1 = Lina_CTRL_1, Ctrl_2 = Lina_CTRL_2)%>%
  select(! c(Lina_CTRL_1, Lina_CTRL_2))

dwell_filtered2 <- result_df2 %>%
  filter(pos %in% c("A")) %>%
  select(-pos, -name)%>%
  group_by(codon) %>%
  mutate(across(c(Ctrl_1, Ctrl_2), mean, na.rm = TRUE)) %>%
  ungroup() %>%
  distinct(codon, .keep_all = TRUE)

scatter_plot <- ggplot(dwell_filtered2, aes(x = Ctrl_1, y = Ctrl_2)) +
    geom_point(aes(), shape = 21) + 
    scale_fill_identity() +
    scale_size_identity() +
    geom_abline(slope = 1, intercept = 0, color = "black", linetype = "dashed") +
    labs(x = "DTs (Ctrl_1; log2)",
         y = "DTs (Ctrl_2; log2)") +
    geom_text_repel(
      data = dwell_filtered2, aes(label = codon), vjust = -1, color = "black", max.overlaps = Inf,
      nudge_y = 0.1, segment.color = "grey50", segment.size = 0.5, size = 4 ) +
    scale_x_continuous(limits = c(-0.8, 0.6)) +
    scale_y_continuous(limits = c(-0.8, 0.8)) +
    theme_classic(base_family = "Arial") +
    theme(plot.background = element_rect(fill = "transparent", colour = NA),
          panel.background = element_rect(fill = "transparent", colour = NA),
          axis.ticks = element_line(colour = "black"),
          axis.title = element_text(size = 14, face = "plain", color = "black"),
          axis.text = element_text(size = 14, face = "plain", color = "black"),
          legend.title = element_text(size = 14, color = "black", face = "plain"),
          legend.background = element_rect(fill = "transparent", colour = NA),
          legend.text = element_text(size = 14, color = "black", face = "plain"),
          plot.title = element_text(size = 14, color = "black", face = "plain"))
    
  
scatter_plot

special_codons <- c("GAG", "GAA", "GAU", "GAC", "AAG", "CAG", "GUG", "GGA",
                    "AAC", "CUG", "GCC")


dwell_filtered <- result_df %>%
  filter(pos %in% c("A")) %>%
  select(-pos, -name)%>%
  group_by(codon) %>%
  mutate(across(c(CTRL, DOUBLE, ILE, LEU, TRIPLE, VAL), mean, na.rm = TRUE)) %>%
  ungroup() %>%
  distinct(codon, .keep_all = TRUE)


dwell_filtered <- dwell_filtered %>%
  mutate(codon_highlight = ifelse(codon %in% special_codons, "special", "normal"))

dwell_filtered <- dwell_filtered %>%
  mutate(codon = reorder(codon, -CTRL))

# Create the plot
bar_plot <- ggplot(dwell_filtered, aes(x = codon, y = CTRL, fill = codon_highlight)) +
  geom_col(color = "black") +
  scale_fill_manual(values = c("normal" = "gray", "special" = "#377EB8")) +  # blue
  theme_classic(base_family = "Arial") +
  theme(
    plot.background = element_rect(fill = "transparent", colour = NA),
    panel.background = element_rect(fill = "transparent", colour = NA),
    axis.ticks = element_line(colour = "black"),
    axis.title = element_text(size = 14, face = "plain", color = "black"),
    axis.text = element_text(size = 14, face = "plain", color = "black"),
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 8),
    legend.position = "none",  # Remove if you don't want a legend
    plot.title = element_text(size = 14, color = "black", face = "plain")
  ) +
  labs(x = "Codon", y = "DT Ctrl (log2)")

bar_plot


 ggsave(
    filename = "../Figures/dwell_Ctrl_barplot.png",
    plot = bar_plot,
    width = 6, height = 3, units = "in", dpi = 300)
```


